#############################################################################
# Makefile for building: Il_fuorisede_disperato
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  Il_fuorisede_disperato.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Il_fuorisede_disperato.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Il_fuorisede_disperato1.0.0
DISTDIR = /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/.tmp/Il_fuorisede_disperato1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Controller/FileCPP/dbcontroller.cpp \
		Model/FileCPP/Utenti.cpp \
		Model/FileCPP/Item.cpp \
		Model/FileCPP/Casa.cpp \
		Model/FileCPP/Cibo.cpp \
		Model/FileCPP/Libri.cpp \
		Model/FileCPP/Trasporto.cpp \
		Model/FileCPP/Vestiti.cpp \
		Database/database.cpp \
		View/FileCPP/aggiungiItem.cpp \
		View/FileCPP/carrello.cpp \
		View/FileCPP/home.cpp \
		View/FileCPP/login.cpp \
		View/FileCPP/main.cpp \
		View/FileCPP/loginForm.cpp \
		View/FileCPP/profile.cpp \
		View/FileCPP/registrazione.cpp \
		View/FileCPP/hamburgermenu.cpp \
		View/FileCPP/modificaItem.cpp \
		View/FileCPP/itemWidget.cpp \
		View/FileCPP/VisitorItem.cpp \
		View/FileCPP/scrollWidget.cpp qrc_resources.cpp \
		moc_aggiungiItem.cpp \
		moc_carrello.cpp \
		moc_home.cpp \
		moc_login.cpp \
		moc_loginForm.cpp \
		moc_profile.cpp \
		moc_registrazione.cpp \
		moc_hamburgermenu.cpp \
		moc_modificaItem.cpp \
		moc_itemWidget.cpp \
		moc_scrollWidget.cpp
OBJECTS       = dbcontroller.o \
		Utenti.o \
		Item.o \
		Casa.o \
		Cibo.o \
		Libri.o \
		Trasporto.o \
		Vestiti.o \
		database.o \
		aggiungiItem.o \
		carrello.o \
		home.o \
		login.o \
		main.o \
		loginForm.o \
		profile.o \
		registrazione.o \
		hamburgermenu.o \
		modificaItem.o \
		itemWidget.o \
		VisitorItem.o \
		scrollWidget.o \
		qrc_resources.o \
		moc_aggiungiItem.o \
		moc_carrello.o \
		moc_home.o \
		moc_login.o \
		moc_loginForm.o \
		moc_profile.o \
		moc_registrazione.o \
		moc_hamburgermenu.o \
		moc_modificaItem.o \
		moc_itemWidget.o \
		moc_scrollWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Il_fuorisede_disperato.pro Controller/FileH/dbcontroller.h \
		Model/FileH/Utenti.h \
		Model/FileH/Item.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Libri.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/VisitorItemInterface.h \
		Database/database.h \
		View/FileH/aggiungiItem.h \
		View/FileH/carrello.h \
		View/FileH/home.h \
		View/FileH/login.h \
		View/FileH/loginForm.h \
		View/FileH/profile.h \
		View/FileH/registrazione.h \
		View/FileH/hamburgermenu.h \
		View/FileH/modificaItem.h \
		View/FileH/itemWidget.h \
		View/FileH/VisitorItem.h \
		View/FileH/scrollWidget.h Controller/FileCPP/dbcontroller.cpp \
		Model/FileCPP/Utenti.cpp \
		Model/FileCPP/Item.cpp \
		Model/FileCPP/Casa.cpp \
		Model/FileCPP/Cibo.cpp \
		Model/FileCPP/Libri.cpp \
		Model/FileCPP/Trasporto.cpp \
		Model/FileCPP/Vestiti.cpp \
		Database/database.cpp \
		View/FileCPP/aggiungiItem.cpp \
		View/FileCPP/carrello.cpp \
		View/FileCPP/home.cpp \
		View/FileCPP/login.cpp \
		View/FileCPP/main.cpp \
		View/FileCPP/loginForm.cpp \
		View/FileCPP/profile.cpp \
		View/FileCPP/registrazione.cpp \
		View/FileCPP/hamburgermenu.cpp \
		View/FileCPP/modificaItem.cpp \
		View/FileCPP/itemWidget.cpp \
		View/FileCPP/VisitorItem.cpp \
		View/FileCPP/scrollWidget.cpp
QMAKE_TARGET  = Il_fuorisede_disperato
DESTDIR       = 
TARGET        = Il_fuorisede_disperato


first: all
####### Build rules

Il_fuorisede_disperato:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Il_fuorisede_disperato.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Il_fuorisede_disperato.pro \
		resources.qrc
	$(QMAKE) -o Makefile Il_fuorisede_disperato.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Il_fuorisede_disperato.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile Il_fuorisede_disperato.pro

qmake_all: FORCE


all: Makefile Il_fuorisede_disperato

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Controller/FileH/dbcontroller.h Model/FileH/Utenti.h Model/FileH/Item.h Model/FileH/DoubleList.h Model/FileH/Casa.h Model/FileH/Cibo.h Model/FileH/Libri.h Model/FileH/Trasporto.h Model/FileH/Vestiti.h Model/FileH/VisitorItemInterface.h Database/database.h View/FileH/aggiungiItem.h View/FileH/carrello.h View/FileH/home.h View/FileH/login.h View/FileH/loginForm.h View/FileH/profile.h View/FileH/registrazione.h View/FileH/hamburgermenu.h View/FileH/modificaItem.h View/FileH/itemWidget.h View/FileH/VisitorItem.h View/FileH/scrollWidget.h $(DISTDIR)/
	$(COPY_FILE) --parents Controller/FileCPP/dbcontroller.cpp Model/FileCPP/Utenti.cpp Model/FileCPP/Item.cpp Model/FileCPP/Casa.cpp Model/FileCPP/Cibo.cpp Model/FileCPP/Libri.cpp Model/FileCPP/Trasporto.cpp Model/FileCPP/Vestiti.cpp Database/database.cpp View/FileCPP/aggiungiItem.cpp View/FileCPP/carrello.cpp View/FileCPP/home.cpp View/FileCPP/login.cpp View/FileCPP/main.cpp View/FileCPP/loginForm.cpp View/FileCPP/profile.cpp View/FileCPP/registrazione.cpp View/FileCPP/hamburgermenu.cpp View/FileCPP/modificaItem.cpp View/FileCPP/itemWidget.cpp View/FileCPP/VisitorItem.cpp View/FileCPP/scrollWidget.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		Database/DatabasePAO.db \
		Immagini/eyeIcon.png \
		Immagini/libro.png \
		Immagini/casa.png \
		Immagini/panino.png \
		Immagini/catalogo.png \
		Immagini/add.png \
		Immagini/maglia.png \
		Immagini/carrello.png \
		Immagini/modifica.png \
		Immagini/bus.png \
		Immagini/exit.png \
		Immagini/profile.png \
		Immagini/notEyeIcon.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_aggiungiItem.cpp moc_carrello.cpp moc_home.cpp moc_login.cpp moc_loginForm.cpp moc_profile.cpp moc_registrazione.cpp moc_hamburgermenu.cpp moc_modificaItem.cpp moc_itemWidget.cpp moc_scrollWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aggiungiItem.cpp moc_carrello.cpp moc_home.cpp moc_login.cpp moc_loginForm.cpp moc_profile.cpp moc_registrazione.cpp moc_hamburgermenu.cpp moc_modificaItem.cpp moc_itemWidget.cpp moc_scrollWidget.cpp
moc_aggiungiItem.cpp: View/FileH/aggiungiItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Cibo.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Utenti.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/aggiungiItem.h -o moc_aggiungiItem.cpp

moc_carrello.cpp: View/FileH/carrello.h \
		Model/FileH/Utenti.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Controller/FileH/dbcontroller.h \
		View/FileH/scrollWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/carrello.h -o moc_carrello.cpp

moc_home.cpp: View/FileH/home.h \
		Model/FileH/Utenti.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Controller/FileH/dbcontroller.h \
		View/FileH/scrollWidget.h \
		View/FileH/hamburgermenu.h \
		View/FileH/aggiungiItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		View/FileH/profile.h \
		View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Database/database.h \
		View/FileH/carrello.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/home.h -o moc_home.cpp

moc_login.cpp: View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Model/FileH/Utenti.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/login.h -o moc_login.cpp

moc_loginForm.cpp: View/FileH/loginForm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/loginForm.h -o moc_loginForm.cpp

moc_profile.cpp: View/FileH/profile.h \
		View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Model/FileH/Utenti.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		View/FileH/carrello.h \
		View/FileH/scrollWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/profile.h -o moc_profile.cpp

moc_registrazione.cpp: View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Model/FileH/Utenti.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/registrazione.h -o moc_registrazione.cpp

moc_hamburgermenu.cpp: View/FileH/hamburgermenu.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Utenti.h \
		View/FileH/aggiungiItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/hamburgermenu.h -o moc_hamburgermenu.cpp

moc_modificaItem.cpp: View/FileH/modificaItem.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Utenti.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/modificaItem.h -o moc_modificaItem.cpp

moc_itemWidget.cpp: View/FileH/itemWidget.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Utenti.h \
		Model/FileH/DoubleList.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/itemWidget.h -o moc_itemWidget.cpp

moc_scrollWidget.cpp: View/FileH/scrollWidget.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Utenti.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/anna/Scrivania/uni/ifd/Il_fuorisede_disperato -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include View/FileH/scrollWidget.h -o moc_scrollWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

dbcontroller.o: Controller/FileCPP/dbcontroller.cpp Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Utenti.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbcontroller.o Controller/FileCPP/dbcontroller.cpp

Utenti.o: Model/FileCPP/Utenti.cpp Model/FileH/Utenti.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utenti.o Model/FileCPP/Utenti.cpp

Item.o: Model/FileCPP/Item.cpp Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item.o Model/FileCPP/Item.cpp

Casa.o: Model/FileCPP/Casa.cpp Model/FileH/Casa.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Casa.o Model/FileCPP/Casa.cpp

Cibo.o: Model/FileCPP/Cibo.cpp Model/FileH/Cibo.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cibo.o Model/FileCPP/Cibo.cpp

Libri.o: Model/FileCPP/Libri.cpp Model/FileH/Libri.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Libri.o Model/FileCPP/Libri.cpp

Trasporto.o: Model/FileCPP/Trasporto.cpp Model/FileH/Trasporto.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Trasporto.o Model/FileCPP/Trasporto.cpp

Vestiti.o: Model/FileCPP/Vestiti.cpp Model/FileH/Vestiti.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vestiti.o Model/FileCPP/Vestiti.cpp

database.o: Database/database.cpp Database/database.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		Model/FileH/DoubleList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o Database/database.cpp

aggiungiItem.o: View/FileCPP/aggiungiItem.cpp View/FileH/aggiungiItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Cibo.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Utenti.h \
		View/FileH/home.h \
		View/FileH/scrollWidget.h \
		View/FileH/hamburgermenu.h \
		View/FileH/profile.h \
		View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Database/database.h \
		View/FileH/carrello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aggiungiItem.o View/FileCPP/aggiungiItem.cpp

carrello.o: View/FileCPP/carrello.cpp View/FileH/home.h \
		Model/FileH/Utenti.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Controller/FileH/dbcontroller.h \
		View/FileH/scrollWidget.h \
		View/FileH/hamburgermenu.h \
		View/FileH/aggiungiItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		View/FileH/profile.h \
		View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Database/database.h \
		View/FileH/carrello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carrello.o View/FileCPP/carrello.cpp

home.o: View/FileCPP/home.cpp View/FileH/home.h \
		Model/FileH/Utenti.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Controller/FileH/dbcontroller.h \
		View/FileH/scrollWidget.h \
		View/FileH/hamburgermenu.h \
		View/FileH/aggiungiItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		View/FileH/profile.h \
		View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Database/database.h \
		View/FileH/carrello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o home.o View/FileCPP/home.cpp

login.o: View/FileCPP/login.cpp View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Model/FileH/Utenti.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		View/FileH/home.h \
		View/FileH/scrollWidget.h \
		View/FileH/hamburgermenu.h \
		View/FileH/aggiungiItem.h \
		View/FileH/profile.h \
		View/FileH/carrello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o View/FileCPP/login.cpp

main.o: View/FileCPP/main.cpp View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Model/FileH/Utenti.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o View/FileCPP/main.cpp

loginForm.o: View/FileCPP/loginForm.cpp View/FileH/loginForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginForm.o View/FileCPP/loginForm.cpp

profile.o: View/FileCPP/profile.cpp View/FileH/profile.h \
		View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Model/FileH/Utenti.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		View/FileH/carrello.h \
		View/FileH/scrollWidget.h \
		View/FileH/home.h \
		View/FileH/hamburgermenu.h \
		View/FileH/aggiungiItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profile.o View/FileCPP/profile.cpp

registrazione.o: View/FileCPP/registrazione.cpp View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Model/FileH/Utenti.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Database/database.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Libri.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		View/FileH/login.h \
		View/FileH/home.h \
		View/FileH/scrollWidget.h \
		View/FileH/hamburgermenu.h \
		View/FileH/aggiungiItem.h \
		View/FileH/profile.h \
		View/FileH/carrello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registrazione.o View/FileCPP/registrazione.cpp

hamburgermenu.o: View/FileCPP/hamburgermenu.cpp View/FileH/hamburgermenu.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Utenti.h \
		View/FileH/aggiungiItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		View/FileH/home.h \
		View/FileH/scrollWidget.h \
		View/FileH/profile.h \
		View/FileH/login.h \
		View/FileH/registrazione.h \
		View/FileH/loginForm.h \
		Database/database.h \
		View/FileH/carrello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hamburgermenu.o View/FileCPP/hamburgermenu.cpp

modificaItem.o: View/FileCPP/modificaItem.cpp View/FileH/modificaItem.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/DoubleList.h \
		Model/FileH/Utenti.h \
		View/FileH/scrollWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modificaItem.o View/FileCPP/modificaItem.cpp

itemWidget.o: View/FileCPP/itemWidget.cpp View/FileH/itemWidget.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Utenti.h \
		Model/FileH/DoubleList.h \
		View/FileH/scrollWidget.h \
		Controller/FileH/dbcontroller.h \
		View/FileH/VisitorItem.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Libri.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemWidget.o View/FileCPP/itemWidget.cpp

VisitorItem.o: View/FileCPP/VisitorItem.cpp View/FileH/VisitorItem.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/Casa.h \
		Model/FileH/Item.h \
		Model/FileH/Cibo.h \
		Model/FileH/Libri.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Vestiti.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisitorItem.o View/FileCPP/VisitorItem.cpp

scrollWidget.o: View/FileCPP/scrollWidget.cpp View/FileH/scrollWidget.h \
		Model/FileH/Item.h \
		Model/FileH/VisitorItemInterface.h \
		Model/FileH/DoubleList.h \
		Controller/FileH/dbcontroller.h \
		Model/FileH/Utenti.h \
		View/FileH/itemWidget.h \
		View/FileH/modificaItem.h \
		Model/FileH/Trasporto.h \
		Model/FileH/Casa.h \
		Model/FileH/Cibo.h \
		Model/FileH/Vestiti.h \
		Model/FileH/Libri.h \
		View/FileH/carrello.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scrollWidget.o View/FileCPP/scrollWidget.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_aggiungiItem.o: moc_aggiungiItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aggiungiItem.o moc_aggiungiItem.cpp

moc_carrello.o: moc_carrello.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_carrello.o moc_carrello.cpp

moc_home.o: moc_home.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_home.o moc_home.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_loginForm.o: moc_loginForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginForm.o moc_loginForm.cpp

moc_profile.o: moc_profile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profile.o moc_profile.cpp

moc_registrazione.o: moc_registrazione.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registrazione.o moc_registrazione.cpp

moc_hamburgermenu.o: moc_hamburgermenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hamburgermenu.o moc_hamburgermenu.cpp

moc_modificaItem.o: moc_modificaItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modificaItem.o moc_modificaItem.cpp

moc_itemWidget.o: moc_itemWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_itemWidget.o moc_itemWidget.cpp

moc_scrollWidget.o: moc_scrollWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scrollWidget.o moc_scrollWidget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Il_fuorisede_disperato/bin || mkdir -p $(INSTALL_ROOT)/opt/Il_fuorisede_disperato/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Il_fuorisede_disperato/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Il_fuorisede_disperato/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Il_fuorisede_disperato/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Il_fuorisede_disperato/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

